### ISSUE TITLE
Transip: Soap Api depricated next spring

### ISSUE THREAD

**Issue by roru69** [RickxZen/transip#1]
Hi,

Me and some other people i know are using this script for a long time now, but TransIP is moving to the Rest-api.
Is there any possibility that you can rewrite this script to use the new Rest-api?

Regards, RR69

**Comment by RickxZen** [comment]
Hello I got the e-mail too. I will try to rebuild but no promises.

**Comment by RickxZen** [comment]
Hi I've been playing with the Rest API and created a new release. This fits for my needs. Please change for ur needs.

Follow instructions: https://github.com/RickxZen/transip#usage

https://github.com/RickxZen/transip/releases/tag/V2.0
