### ISSUE TITLE
A record gets updated, content of TXT record doesn't

### ISSUE THREAD

**Issue by roru69** [RickxZen/transip#2]
Hi,

I installed the script on my Server and it works like it should. Thanks for that.

But i'm no programmer at all so I wanted to ask you (if you have the time) to look into this small problem.

I have a TXT record where the content isn't updated with the new address.

v=spf1 mx a ip4:192.168.0.1/32 ~all

I know this is a feature request, but as I said, I.m not a programmer....

Regards RR69

**Comment by RickxZen** [comment]
Hi I'm sorry this script isn't meant for updating TXT records, also I don't think the old script updated TXT records. 

As it filters in the foreach the A records with the following line (48): 
if (($dnsEntry->getType() == 'A') && $dnsEntry->getContent() != $ipAddress)

You could add another if statement in the foreach loop where you filter for your TXT records and from there figure out how to replace part of the content. 

Good luck.
